name: Proceedings - Project Summary
description: Project Summary for the OHBM Hackathon 2023 Proceedings
labels:
  - Proceedings
assignees:
  - anibalsolon
  - ufangYang
body:
  - type: markdown
    attributes:
      value: >-
        Please add images in the summary field or via comments on the issue. Add a
        caption of up to 250 characters.
  - type: textarea
    id: authors
    attributes:
      label: Authors
      description: A list of authors and their e-mails.
      placeholder: One author per line, using the format "Author <e-mail>"
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Supports markdown, up to 500 words.
      placeholder: |
        # Introduction
        ...
        # Results
        ...
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: References (Bibtex)
      description: References in the Bibtex format.
